require:
  - standard
  - rubocop-rails
  - rubocop-rspec

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 3.0.3
  NewCops: enable
  Exclude:
    - "bin/**"
    - "db/schema.rb"
    - "vendor/**/*"

RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
